# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "kaorimatz/ubuntu-16.04-amd64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  #config.vm.network "forwarded_port", guest: 22, host: 22222

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "10.0.0.6", auto_config: false, virtualbox__intnet: "InfSec_LAN"
  # And since vagrant has trouble with additional interfaces in Ubuntu 16.04, also add manually the interface:
  config.vm.provision 'shell', inline: "ifconfig eth1 10.0.0.6; ifconfig eth1 up"
  config.vm.provision 'shell', inline: "route del default"
  config.vm.provision 'shell', inline: "route add default gw 10.0.0.1 eth1"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get dist-upgrade -y
    apt-get install -y iptables
    apt-get install -y unzip
  SHELL

  config.vm.provision "shell", path: "hardening.sh"
  config.vm.provision "shell", path: "add_new_user.sh"
  config.vm.provision "file", source: "decrypt.sh", destination: "/home/vagrant/decrypt.sh"
  config.vm.provision "file", source: "manage_backup.sh", destination: "/home/vagrant/manage_backup.sh"
  config.vm.provision "shell", path: "cron.sh", privileged: false

  id_rsa_key_pub = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyVTafuR1rnt4wmqVdjzc7x3LYhubxpW9Ew0YXAvde5FpplDnoMXhWY/9q8CRLeGgOEo1HY0ceWBL9IS5OKpfqnPYAtjAE5xMmTd0TfMVrtD0xplLOpXjpaiCwyMGoucWY58V3JNucAfixe9sU6SGl+xGy1La6syN/HIL18yrXKuLIgQ/RuCgw6TXxiNEa8/xXa1o3+Q9/hxDb9ONky5G00kxPUcxJPOgMGdBz2ev/d0IrkeQvs0wXEjQOmiotPJzimpjMkAm6/WL2SmyAmG3HxXc9NqNUBD0ft5pMFz2bH2ivE/Ga20nAksjRSpd7Ife4PBtp5PycuInCqFZGfve8oDE16g6a6nHU1mkkrfDlBh8OuqnuC1gYvcwtEnYbkdNAFjQx2GCfMA7E7SqT5fIG3ZSk5D6Ua50owMq7gIo1RNUto3ldYwczotYIynRZ5t6Il5bnIDc3V9Mxo9fVx/njsXRjdaSKZLz/BARyngSKo/6Yq0ixUnYvQtjsFRwm1DsIz0BJTOfGjc6GcBoMwT7fPXDiqu0W8RslsSNFePqJ+8z0ziMDXxvQVflHRFIOVMRd9F9s+S00htgYYzOUIqOlamlXLxTCKgfGuzzdFWl8ydytIYU3tooRlp5WW7Ln3g7Xd9UU9EWfFdq1ZHUCA5uGOcVQUCCy8J/PifPUuC5UOQ== backup@imovies.com"

  config.vm.provision :shell,
          :inline => "echo 'appending SSH Pub Key to ~/imovies-backup/.ssh/authorized_keys' && echo '#{id_rsa_key_pub }' >> /home/imovies-backup/.ssh/authorized_keys && chmod 600 /home/imovies-backup/.ssh/authorized_keys && chown imovies-backup:imovies-backup /home/imovies-backup/.ssh/authorized_keys"

  @keys = Dir.entries('../ssh_public_keys/')
  for key in @keys
    next if key == '.' or key == '..'
    content = File.open("../ssh_public_keys/#{key}", 'r').read
    config.vm.provision :shell, :inline => "echo '#{content}' >> /home/vagrant/.ssh/authorized_keys"
  end

  config.vm.provision "shell", inline: <<-SHELL
    chmod 600 /home/vagrant/.ssh/authorized_keys
  SHELL


  config.vm.provision "file", source: "../sshd_config", destination: "/home/vagrant/sshd_config"
  config.vm.provision "shell", inline: <<-SHELL
    cp /home/vagrant/sshd_config /etc/ssh/sshd_config
    rm /home/vagrant/sshd_config
    service ssh restart
  SHELL

end
