# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "kaorimatz/ubuntu-16.04-amd64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "192.168.1.5", auto_config: false, virtualbox__intnet: "InfSec"
  # And since vagrant has trouble with additional interfaces in Ubuntu 16.04, also add manually the interface:
  config.vm.provision 'shell', inline: "ifconfig eth1 192.168.1.5; ifconfig eth1 up"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    apt-get install -y iptables
    apt-get install -y nano
    apt-get install -y vim
    debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
    debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
    apt-get install -y mysql-server
    apt-get -y remove apache2
    SHELL

  config.vm.provision "file", source: "./imovies_users.dump", destination: "/home/vagrant/imovies_users.dump"
  config.vm.provision "shell", path: "setup_db.sh"

  config.vm.provision "file", source: "./keys/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: "./keys/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision "file", source: "./keys/bak_rsa.pub.pem", destination: "/home/vagrant/.ssh/bak_rsa.pub.pem"
  config.vm.provision "shell", path: "hardening.sh"

  config.vm.provision "shell", inline: <<-SHELL
    service mysql restart
  SHELL

  ## add ssh key from webserver
  for_db = File.open("./for_db.pub", 'r').read
  config.vm.provision :shell, :inline => "echo '#{for_db}' >> /home/vagrant/.ssh/authorized_keys"


  @keys = Dir.entries('../ssh_public_keys/')
  for key in @keys
    next if key == '.' or key == '..'
    content = File.open("../ssh_public_keys/#{key}", 'r').read
    config.vm.provision :shell, :inline => "echo '#{content}' >> /home/vagrant/.ssh/authorized_keys"
  end

  config.vm.provision "shell", inline: <<-SHELL
    chmod 600 /home/vagrant/.ssh/authorized_keys
  SHELL

  config.vm.provision "file", source: "../sshd_config", destination: "/home/vagrant/sshd_config"
  config.vm.provision "shell", inline: <<-SHELL
    cp /home/vagrant/sshd_config /etc/ssh/sshd_config
    rm /home/vagrant/sshd_config
    service ssh restart
  SHELL

  ## Remove user vagrant from sudoers file
  ## and also remove ssh key of vagrant
  config.vm.provision "shell", inline: <<-SHELL
  #  sudo rm /etc/sudoers.d/vagrant
    sed -E -i '/^ssh-rsa.+vagrant/d' ~/.ssh/authorized_keys
  SHELL
end
